// documents/code/implementations/common/color.svelte
<script>
	// npm install --save-dev @iconify/svelte @iconify/icons-bi @iconify/icons-bx @iconify/icons-noto
	import IconifyIcon from '@iconify/svelte';
	import bellFill from '@iconify/icons-bi/bell-fill';
	import stopwatchIcon from '@iconify/icons-bi/stopwatch';
	import bxHome from '@iconify/icons-bx/bx-home';
	import paintbrushIcon from '@iconify/icons-noto/paintbrush';
</script>

<style>
	/* 
		Cannot target component in CSS, target SVG 
		instead using Svelte's :global() function 
	*/
	div :global(svg) {
		vertical-align: -0.125em;
	}

	/* Change text color for ".orange-block" to #e70 */
	.orange-block {
		color: #e70;
	}
	/* Change all icons inside ".light-blue-block" to #08f */
	/*
		Must use :global() because Svelte cannot assign style to
		a component, so need to target SVG generated by component.
	*/
	.light-blue-block :global(svg) {
		color: #08f;
	}

	/* Change text color for ".red-icon" to #e00 */
	/*
		Must use :global() because Svelte cannot assign style to a
		component by class name, it can only work with standard HTML tags.
	*/
	div :global(.red-icon) {
		color: #e00;
	}
</style>

<div>
	<div class="light-blue-block">
		All icons inside this div are light blue, including a bell icon
		<IconifyIcon icon={bellFill} />
		and stopwatch icon
		<IconifyIcon icon={stopwatchIcon} />
	</div>
	<div class="orange-block">
		This text and icon are orange:
		<IconifyIcon icon={bellFill} />
	</div>
	<div>
		Red home icons (shows different ways to change color):
		<IconifyIcon class="red-icon" icon={bxHome} />
		<IconifyIcon style="color: red" icon={bxHome} />
		<IconifyIcon color="red" icon={bxHome} />
	</div>
	<div>
		Icon with palette:
		<IconifyIcon icon={paintbrushIcon} />
	</div>
</div>

// documents/code/implementations/vue2/color.vue
<template>
	<div>
		<div class="light-blue-block">
			All icons inside this div are light blue, including a bell icon
			<IconifyIcon :icon="icons.bellFill" :inline="true" />and stopwatch icon
			<IconifyIcon :icon="icons.stopwatch" :inline="true" />
		</div>
		<div class="orange-block">
			This text and icon are orange:
			<IconifyIcon :icon="icons.bellFill" :inline="true" />
		</div>
		<div>
			Red home icons (shows different ways to change color):
			<IconifyIcon class="red-icon" :icon="icons.bxHome" :inline="true" />
			<IconifyIcon :style="{ color: 'red' }" :icon="icons.bxHome" :inline="true" />
			<IconifyIcon color="red" :icon="icons.bxHome" :inline="true" />
		</div>
		<div>
			Icon with palette:
			<IconifyIcon :icon="icons.paintbrush" :inline="true" />
		</div>
	</div>
</template>

<script>
// npm install --save-dev @iconify/vue@1 @iconify-icons/bi @iconify-icons/bx @iconify-icons/noto
import IconifyIcon from '@iconify/vue';
import bellFill from '@iconify-icons/bi/bell-fill';
import stopwatchIcon from '@iconify-icons/bi/stopwatch';
import bxHome from '@iconify-icons/bx/bx-home';
import paintbrushIcon from '@iconify-icons/noto/paintbrush';

export default {
	components: {
		IconifyIcon,
	},
	data() {
		return {
			icons: {
				bellFill: bellFill,
				stopwatch: stopwatchIcon,
				bxHome: bxHome,
				paintbrush: paintbrushIcon,
			},
		};
	},
};
</script>
